In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.3.2

In [4]:
trips = pd.read_csv("./metro_trips.csv")

In [5]:
trips.head()

,Trip_ID,Service_Date,Train_ID,Route_ID,Origin_Station,Destination_Station,Scheduled_Departure,Actual_Departure,Scheduled_Arrival,Actual_Arrival,Passenger_Count,Distance_KM,Fare,Trip_Status
0,TP000001,2026-02-21,TR0120,R03,ST020,ST003,2026-02-21 22:00,2026-02-21 22:02,2026-02-21 23:04,2026-02-21 23:08,328.0,7.82,87.17,Completed
1,TP000002,2026-04-10,TR0052,R08,ST030,ST051,2026-04-10 06:00,2026-04-10 06:03,2026-04-10 06:18,2026-04-10 06:25,681.0,28.75,33.98,Completed
2,TP000003,2026-03-17,TR0004,R04,ST039,ST053,2026-03-17 09:40,2026-03-17 09:40,2026-03-17 10:18,2026-03-17 10:18,173.0,22.51,42.42,Completed
3,TP000004,2026-04-29,TR0054,R01,ST012,ST034,2026-04-29 10:30,2026-04-29 10:31,2026-04-29 10:58,2026-04-29 10:58,647.0,26.22,110.63,Completed
4,TP000005,2026-02-01,TR0021,R02,ST012,ST041,2026-02-01 08:00,2026-02-01 08:08,2026-02-01 09:10,2026-02-01 09:23,872.0,37.89,102.48,Completed

In [6]:
stations = pd.read_csv("./metro_stations.csv")
stations.head()

,Station_ID,Station_Name,Line,Zone,Latitude,Longitude,Daily_Capacity,Station_Type
0,ST001,Hyderabad Central 01,Red,Z1,13.784141,80.199566,17233,Regular
1,ST002,Bengaluru Central 02,Blue,Z2,14.837753,78.774587,20083,Regular
2,ST003,Chennai Central 03,Green,Z3,17.147850,81.525719,27194,Regular
3,ST004,Mumbai Central 04,Purple,Z4,16.390316,78.491514,11966,Regular
4,ST005,Delhi Central 05,Red,Z5,18.118292,81.599251,14910,Interchange

In [11]:
trains = pd.read_csv("./metro_trains.csv")
trains.head()

,Train_ID,Train_Model,Manufacture_Year,Capacity,Coach_Count,Energy_Type,Maintenance_Date,Train_Status
0,TR0001,Metro-X1,2014,1500,6,Electric,2026-03-18,Active
1,TR0002,Metro-X2,2017,900,8,Electric,2026-06-10,Active
2,TR0003,Metro-Pro,2016,1500,4,Electric,2026-04-12,Active
3,TR0004,Metro-EV,2021,1500,8,Hybrid,2026-05-14,Active
4,TR0005,Metro-X1,2015,900,6,Electric,2026-07-07,Active

In [9]:
incidents = pd.read_csv("./metro_incidents.csv")
incidents.head()

,Incident_ID,Trip_ID,Incident_Date,Incident_Type,Severity,Delay_Minutes,Resolution_Minutes,Root_Cause,Resolved_By
0,INC00001,TP006739,2026-07-08,Signal,Low,12,46,External,Control Room
1,INC00002,TP006597,2026-07-30,Medical,High,3,18,Infrastructure,Maintenance
2,INC00003,TP011616,2026-01-09,Weather,Medium,18,36,Infrastructure,Maintenance
3,INC00004,TP005377,2026-03-24,Weather,Low,12,26,Passenger Volume,Control Room
4,INC00005,TP012372,2026-02-28,Door,Medium,12,14,Passenger Volume,Security

In [12]:
print(trips.shape)
print(stations.shape)
print(trains.shape)
print(incidents.shape)

(20000, 14)
(60, 8)
(120, 8)
(1800, 9)

In [13]:
print(trips.columns)

Index(['Trip_ID', 'Service_Date', 'Train_ID', 'Route_ID', 'Origin_Station',
       'Destination_Station', 'Scheduled_Departure', 'Actual_Departure',
       'Scheduled_Arrival', 'Actual_Arrival', 'Passenger_Count', 'Distance_KM',
       'Fare', 'Trip_Status'],
      dtype='object')

In [14]:
trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Trip_ID              20000 non-null  object
 1   Service_Date         20000 non-null  object
 2   Train_ID             20000 non-null  object
 3   Route_ID             20000 non-null  object
 4   Origin_Station       20000 non-null  object
 5   Destination_Station  20000 non-null  object
 6   Scheduled_Departure  20000 non-null  object
 7   Actual_Departure     20000 non-null  object
 8   Scheduled_Arrival    20000 non-null  object
 9   Actual_Arrival       20000 non-null  object
 10  Passenger_Count      19980 non-null  float64
 11  Distance_KM          20000 non-null  float64
 12  Fare                 20000 non-null  float64
 13  Trip_Status          20000 non-null  object
dtypes: float64(3), object(11)
memory usage: 2.1+ MB

In [15]:
stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Station_ID      60 non-null     object
 1   Station_Name    60 non-null     object
 2   Line            60 non-null     object
 3   Zone            60 non-null     object
 4   Latitude        60 non-null     float64
 5   Longitude       60 non-null     float64
 6   Daily_Capacity  60 non-null     int64
 7   Station_Type    60 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 3.9+ KB

In [16]:
trains.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Train_ID          120 non-null    object
 1   Train_Model       120 non-null    object
 2   Manufacture_Year  120 non-null    int64
 3   Capacity          120 non-null    int64
 4   Coach_Count       120 non-null    int64
 5   Energy_Type       120 non-null    object
 6   Maintenance_Date  120 non-null    object
 7   Train_Status      120 non-null    object
dtypes: int64(3), object(5)
memory usage: 7.6+ KB

In [17]:
incidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Incident_ID         1800 non-null   object
 1   Trip_ID             1800 non-null   object
 2   Incident_Date       1800 non-null   object
 3   Incident_Type       1800 non-null   object
 4   Severity            1800 non-null   object
 5   Delay_Minutes       1800 non-null   int64
 6   Resolution_Minutes  1800 non-null   int64
 7   Root_Cause          1800 non-null   object
 8   Resolved_By         1800 non-null   object
dtypes: int64(2), object(7)
memory usage: 126.7+ KB

In [18]:
trips.describe()

       Passenger_Count   Distance_KM          Fare
count     19980.000000  20000.000000  20000.000000
mean        496.811161     25.854391     67.110272
std         207.893806     12.728550     30.467689
min          20.000000      0.000000   -119.940000
25%         347.000000     14.807500     41.120000
50%         461.000000     25.890000     67.220000
75%         623.000000     36.780000     92.890000
max        1332.000000     48.000000    119.990000

In [19]:
trips.isna().sum()

Trip_ID                 0
Service_Date            0
Train_ID                0
Route_ID                0
Origin_Station          0
Destination_Station     0
Scheduled_Departure     0
Actual_Departure        0
Scheduled_Arrival       0
Actual_Arrival          0
Passenger_Count        20
Distance_KM             0
Fare                    0
Trip_Status             0
dtype: int64

checking null values

In [20]:
stations.isna().sum()

Station_ID        0
Station_Name      0
Line              0
Zone              0
Latitude          0
Longitude         0
Daily_Capacity    0
Station_Type      0
dtype: int64

In [21]:
trains.isna().sum()

Train_ID            0
Train_Model         0
Manufacture_Year    0
Capacity            0
Coach_Count         0
Energy_Type         0
Maintenance_Date    0
Train_Status        0
dtype: int64

In [22]:
incidents.isna().sum()

Incident_ID           0
Trip_ID               0
Incident_Date         0
Incident_Type         0
Severity              0
Delay_Minutes         0
Resolution_Minutes    0
Root_Cause            0
Resolved_By           0
dtype: int64

In [23]:
trips.isna().mean() * 100

Trip_ID                0.0
Service_Date           0.0
Train_ID               0.0
Route_ID               0.0
Origin_Station         0.0
Destination_Station    0.0
Scheduled_Departure    0.0
Actual_Departure       0.0
Scheduled_Arrival      0.0
Actual_Arrival         0.0
Passenger_Count        0.1
Distance_KM            0.0
Fare                   0.0
Trip_Status            0.0
dtype: float64

checking duplicate rows

In [24]:
trips.duplicated().sum()

np.int64(0)

In [25]:
stations.duplicated().sum()

np.int64(0)

In [26]:
trains.duplicated().sum()

np.int64(0)

In [27]:
incidents.duplicated().sum()

np.int64(0)

checking primary keys

In [28]:
trips["Trip_ID"].duplicated().sum()

np.int64(0)

In [29]:
stations["Station_ID"].duplicated().sum()

np.int64(0)

In [30]:
trains["Train_ID"].duplicated().sum()

np.int64(0)

In [31]:
incidents["Incident_ID"].duplicated().sum()

np.int64(0)

investigateing the 20 missing passenger counts

In [32]:
trips[trips["Passenger_Count"].isna()]

,Trip_ID,Service_Date,Train_ID,Route_ID,Origin_Station,Destination_Station,Scheduled_Departure,Actual_Departure,Scheduled_Arrival,Actual_Arrival,Passenger_Count,Distance_KM,Fare,Trip_Status
331,TP000332,2026-01-03,TR0112,R05,ST018,ST029,2026-01-03 11:10,2026-01-03 11:18,2026-01-03 12:01,2026-01-03 12:13,NaN,27.62,16.56,Completed
1441,TP001442,2026-05-21,TR0090,R11,ST018,ST050,2026-05-21 08:30,2026-05-21 08:33,2026-05-21 09:25,2026-05-21 09:31,NaN,15.75,23.31,Completed
2757,TP002758,2026-01-12,TR0104,R07,ST010,ST038,2026-01-12 14:30,2026-01-12 14:33,2026-01-12 14:56,2026-01-12 14:58,NaN,24.81,119.03,Completed
3585,TP003586,2026-05-24,TR0018,R04,ST049,ST023,2026-05-24 12:30,2026-05-24 12:48,2026-05-24 13:09,2026-05-24 13:25,NaN,28.06,89.32,Completed
6488,TP006489,2026-03-17,TR0045,R06,ST048,ST044,2026-03-17 22:20,2026-03-17 22:25,2026-03-17 23:32,2026-03-17 23:36,NaN,28.54,50.54,Completed
8457,TP008458,2026-01-25,TR0113,R09,ST025,ST018,2026-01-25 07:30,2026-01-25 07:31,2026-01-25 08:40,2026-01-25 08:41,NaN,38.83,32.20,Completed
8584,TP008585,2026-05-02,TR0051,R09,ST026,ST049,2026-05-02 23:40,2026-05-02 23:40,2026-05-03 00:27,2026-05-03 00:32,NaN,42.61,89.59,Completed
8954,TP008955,2026-07-13,TR0058,R07,ST007,ST050,2026-07-13 14:30,2026-07-13 14:35,2026-07-13 15:26,2026-07-13 15:31,NaN,21.50,20.95,Delayed
10686,TP010687,2026-01-02,TR0028,R07,ST035,ST042,2026-01-02 07:00,2026-01-02 07:03,2026-01-02 07:48,2026-01-02 07:56,NaN,18.27,78.16,Completed
12550,TP012551,2026-07-31,TR0068,R04,ST008,ST017,2026-07-31 17:30,2026-07-31 17:42,2026-07-31 17:47,2026-07-31 18:02,NaN,42.84,68.19,Completed
14539,TP014540,2026-06-07,TR0004,R06,ST040,ST059,2026-06-07 15:20,2026-06-07 15:23,2026-06-07 16:13,2026-06-07 16:15,NaN,42.07,100.85,Completed
14602,TP014603,2026-02-23,TR0095,R11,ST005,ST006,2026-02-23 17:10,2026-02-23 17:12,2026-02-23 17:46,2026-02-23 17:53,NaN,29.15,106.12,Completed
14905,TP014906,2026-03-02,TR0071,R04,ST055,ST041,2026-03-02 17:10,2026-03-02 17:10,2026-03-02 17:47,2026-03-02 17:51,NaN,18.90,39.66,Completed
15140,TP015141,2026-03-07,TR0021,R03,ST036,ST033,2026-03-07 18:50,2026-03-07 18:50,2026-03-07 20:04,2026-03-07 20:08,NaN,16.31,91.28,Cancelled
15202,TP015203,2026-02-19,TR0008,R05,ST042,ST004,2026-02-19 08:30,2026-02-19 08:30,2026-02-19 09:43,2026-02-19 09:44,NaN,19.07,90.03,Completed
15416,TP015417,2026-07-06,TR0081,R06,ST025,ST046,2026-07-06 13:00,2026-07-06 13:01,2026-07-06 14:14,2026-07-06 14:15,NaN,41.63,52.50,Completed
15663,TP015664,2026-04-18,TR0009,R12,ST029,ST016,2026-04-18 14:10,2026-04-18 14:13,2026-04-18 15:14,2026-04-18 15:17,NaN,43.32,26.12,Completed
17133,TP017134,2026-08-06,TR0113,R04,ST054,ST007,2026-08-06 18:30,2026-08-06 18:38,2026-08-06 19:35,2026-08-06 19:46,NaN,20.24,44.66,Completed
19205,TP019206,2026-07-09,TR0017,R12,ST029,ST060,2026-07-09 15:00,2026-07-09 15:08,2026-07-09 15:57,2026-07-09 16:09,NaN,5.19,98.62,Completed
19474,TP019475,2026-08-05,TR0063,R06,ST029,ST051,2026-08-05 06:40,2026-08-05 06:40,2026-08-05 07:16,2026-08-05 07:16,NaN,46.34,47.54,Cancelled

In [33]:
trips[trips["Passenger_Count"].isna()][
    ["Trip_ID", "Service_Date", "Train_ID", "Route_ID",
     "Origin_Station", "Destination_Station", "Fare", "Distance_KM"]
]

,Trip_ID,Service_Date,Train_ID,Route_ID,Origin_Station,Destination_Station,Fare,Distance_KM
331,TP000332,2026-01-03,TR0112,R05,ST018,ST029,16.56,27.62
1441,TP001442,2026-05-21,TR0090,R11,ST018,ST050,23.31,15.75
2757,TP002758,2026-01-12,TR0104,R07,ST010,ST038,119.03,24.81
3585,TP003586,2026-05-24,TR0018,R04,ST049,ST023,89.32,28.06
6488,TP006489,2026-03-17,TR0045,R06,ST048,ST044,50.54,28.54
8457,TP008458,2026-01-25,TR0113,R09,ST025,ST018,32.20,38.83
8584,TP008585,2026-05-02,TR0051,R09,ST026,ST049,89.59,42.61
8954,TP008955,2026-07-13,TR0058,R07,ST007,ST050,20.95,21.50
10686,TP010687,2026-01-02,TR0028,R07,ST035,ST042,78.16,18.27
12550,TP012551,2026-07-31,TR0068,R04,ST008,ST017,68.19,42.84
14539,TP014540,2026-06-07,TR0004,R06,ST040,ST059,100.85,42.07
14602,TP014603,2026-02-23,TR0095,R11,ST005,ST006,106.12,29.15
14905,TP014906,2026-03-02,TR0071,R04,ST055,ST041,39.66,18.90
15140,TP015141,2026-03-07,TR0021,R03,ST036,ST033,91.28,16.31
15202,TP015203,2026-02-19,TR0008,R05,ST042,ST004,90.03,19.07
15416,TP015417,2026-07-06,TR0081,R06,ST025,ST046,52.50,41.63
15663,TP015664,2026-04-18,TR0009,R12,ST029,ST016,26.12,43.32
17133,TP017134,2026-08-06,TR0113,R04,ST054,ST007,44.66,20.24
19205,TP019206,2026-07-09,TR0017,R12,ST029,ST060,98.62,5.19
19474,TP019475,2026-08-05,TR0063,R06,ST029,ST051,47.54,46.34

In [34]:
trips[trips["Passenger_Count"].isna()]["Route_ID"].value_counts()

Route_ID
R04    4
R06    4
R07    3
R05    2
R11    2
R09    2
R12    2
R03    1
Name: count, dtype: int64

In [35]:
trips.groupby("Route_ID")["Passenger_Count"].agg(
    ["count", "median", "mean"]
)

          count  median        mean
Route_ID
R01        1667   460.0  498.842831
R02        1722   462.0  499.028455
R03        1694   459.5  496.413223
R04        1658   456.5  495.635706
R05        1726   469.0  500.566628
R06        1699   453.0  486.851677
R07        1623   467.0  499.116451
R08        1607   464.0  500.669571
R09        1624   455.0  489.969828
R10        1662   465.0  501.095066
R11        1626   451.0  488.787823
R12        1672   466.5  504.557416

In [36]:
cleaned_trips = trips.copy()

In [37]:
route_medians = cleaned_trips.groupby("Route_ID")["Passenger_Count"].transform("median")

In [38]:
print(route_medians)

0        459.5
1        464.0
2        456.5
3        460.0
4        462.0
         ...
19995    451.0
19996    456.5
19997    462.0
19998    456.5
19999    455.0
Name: Passenger_Count, Length: 20000, dtype: float64

In [39]:
cleaned_trips["Passenger_Count"] = cleaned_trips["Passenger_Count"].fillna(route_medians)

In [40]:
cleaned_trips["Passenger_Count"].isna().sum()

np.int64(0)

In [41]:
cleaned_trips.shape

(20000, 14)

In [42]:
cleaned_trips.loc[trips["Passenger_Count"].isna(),
                  ["Trip_ID", "Route_ID", "Passenger_Count"]]

        Trip_ID Route_ID  Passenger_Count
331    TP000332      R05            469.0
1441   TP001442      R11            451.0
2757   TP002758      R07            467.0
3585   TP003586      R04            456.5
6488   TP006489      R06            453.0
8457   TP008458      R09            455.0
8584   TP008585      R09            455.0
8954   TP008955      R07            467.0
10686  TP010687      R07            467.0
12550  TP012551      R04            456.5
14539  TP014540      R06            453.0
14602  TP014603      R11            451.0
14905  TP014906      R04            456.5
15140  TP015141      R03            459.5
15202  TP015203      R05            469.0
15416  TP015417      R06            453.0
15663  TP015664      R12            466.5
17133  TP017134      R04            456.5
19205  TP019206      R12            466.5
19474  TP019475      R06            453.0

### Passenger Count Missing-Value Treatment

There were 20 missing values in Passenger_Count. The affected
records were distributed across multiple routes, with no obvious
single-route pattern.

Instead of removing these trips, missing passenger counts were
imputed using the median Passenger_Count of the corresponding
Route_ID. Route-level median imputation was selected because
passenger demand can vary by route and the median is less sensitive
to extreme passenger counts than the mean.

After imputation, Passenger_Count contains no missing values and
the original 20,000 trip records were retained.